### ISSUE TITLE
Fix checking unpatched bzip2

### ISSUE THREAD

**Issue by adamjedrzejewski** [adamjedrzejewski/ToddLinux#6]
While checking bzip2 requirement, the script stops execution and waits.

Installed version: 35010

**Comment by adamjedrzejewski** [comment]
Related to bzip2 writing it's version info to stderr instead of stdout.

**Comment by adamjedrzejewski** [comment]
bzip2 is stupid

**Comment by adamjedrzejewski** [comment]
While checking the bzip2 requirement, unpatched bzip2 will await input which prevents script from continuing, being fed nothing (redirecting /dev/null as input to bzip2) will still write something to output stream, therefore streams cannot be merged.

**Comment by christopher-besch** [comment]
Change `reqs.csv` to JSON with optional parameters.

**Comment by christopher-besch** [comment]
> While checking the bzip2 requirement, unpatched bzip2 will await input which prevents script from continuing, being fed nothing (redirecting /dev/null as input to bzip2) will still write something to output stream, therefore streams cannot be merged.

bzip2 is stupid

**Comment by adamjedrzejewski** [comment]
done: e68ce2e2b7f6b0b2ea388b539ae9aa473dfd158f
